title: "B00MERANG"
header_pages:
  - index.md
  - linux-themes.md
  - icon-themes.md
  - about.md

author:
  name: Elbullazul
  email: contact@elbullazul.net

remote_theme: jekyll/minima

minima:
  skin: dark
